/* eslint-disable max-len */
import { Memory, MemoryConfig } from './types'
import { ContentBlock, userRole } from './vendors/types'

/**
 * Prompt to find memories relevant to a given context
 */
const relevantMemorySearch = (context: ContentBlock[] | string | string[]) => {
    return {
        systemMessage: `You are a memory retrieval agent. Your job is to search a vector store of memories to find context that will help respond to a conversation.

Memories are short informational snippets extracted from past conversations including user preferences, personal details, project context, prior decisions, and institutional knowledge.

## How to search effectively
- Phrase queries as concise topic descriptions or statements, not questions (e.g. "preferred frontend framework" not "what framework do they like?")
- Think about how the information was likely stored, and match that phrasing
- Search for the most specific relevant topics first
- If the conversation touches multiple distinct topics, search for each separately
- Even for seemingly simple requests, consider whether the user might have stored preferences about tone, format, or conventions that would improve the response

## How to select memories
- Search results include a memory ID and content for each match
- After searching, review the results and select only the memories that are genuinely relevant to the current conversation
- Return the IDs of relevant memories in your response
- If no memories are relevant either because search returned nothing useful or because the conversation truly needs no additional context (e.g. a simple "thanks" or "goodbye") return an empty array
- Err on the side of including a memory if it could plausibly improve the response, but do not include memories that are only superficially related`,
        messages: [
            {
                role: userRole,
                content: `<conversation>${JSON.stringify(context)}</conversation>
                
Search for any memories that would help inform a response to this conversation.`,
            },
        ],
        tools: [
            {
                name: 'search_memories',
                description: 'Search the memory vector store. Returns an array of matching memories, or an empty array if none are found.',
                parameters: {
                    type: 'object' as const,
                    properties: {
                        queries: {
                            type: 'array',
                            description: 'The queries to use in the vector store search.',
                            properties: {
                                type: 'string',
                                description: 'Query string to use in the vector store search.',
                            },
                        },
                    },
                    required: [ 'queries' ],
                },
            },
        ],
    }
}

/**
 * Prompt to extract memories from content blocks
 */
const memoryExtraction = (context: ContentBlock[] | string | string[], userId?: string) => {
    return {
        systemMessage: `You extract information from conversations and store it as memories in a vector database for future retrieval.

## What to extract
${userId ? `- User preferences (tone, format, tools, workflows, conventions)
- Personal or professional details the user has shared` : ''}
- Project context, goals, architecture decisions, or constraints
- Institutional knowledge, domain-specific terminology, or conventions
- Information from external sources (tools, websites, documents) that the user found relevant
- Recurring patterns or corrections that indicate how the user wants things done

## What NOT to extract
- Anything generated by the AI/assistant (unless the user explicitly confirmed or endorsed it)
- Ephemeral information that fully served its purpose within the conversation (e.g. a one-off calculation, a typo correction)
- Information that is common knowledge and would not meaningfully improve a future response

## Memory granularity
Each memory should contain exactly one piece of information. If a single statement reveals multiple facts, split them into separate memories.
- "I'm a frontend engineer at Acme and I prefer Vue over React" → two memories: one about their role, one about their framework preference
- "Our API uses REST with JWT auth and rate limits at 1000 req/min" → three memories: protocol, auth method, rate limit
This makes memories easier to deduplicate, update individually, and retrieve without pulling in unrelated context.

## How to write summaries
Summaries are embedded in a vector store and matched against future search queries. Write them as concise, declarative statements capturing exactly one piece of information that would be easy to find via semantic search. Do not combine multiple facts into a single summary. Include the key nouns and concepts someone would search for. Front-load the most important terms.
- Good: "User prefers TypeScript with Zod for schema validation"
- Bad: "The user mentioned they like using Zod"
- Good: "Project uses PostgreSQL with pgvector for memory storage"
- Bad: "Database setup was discussed"`,
        messages: [
            {
                role: userRole,
                content: `<conversation>${JSON.stringify(context)}</conversation>
                
Extract any memories from this conversation that would be valuable for future reference. If nothing worth extracting is present, return an empty memories array.`,
            },
        ],
    }
}

/**
 * Prompt to consider and do memory merge
 */
const memoryMerge = (newMemory: Memory, nearMemory: Memory, memoryConfig: MemoryConfig) => {
    return {
        systemMessage: `You are a memory deduplication agent. You receive an existing memory from a vector store and a candidate new memory that was flagged as potentially overlapping. Your job is to determine the relationship between them and decide how to handle the new information.

## Decision criteria

**Update the existing memory** when the new information:
- Corrects or supersedes the existing information (e.g. a preference changed, a status was updated)
- Adds a small clarifying detail to the same fact (e.g. adding a version number to a known tool preference)

When updating, always prefer the most recent information. Do not preserve outdated facts. If something changed, reflect the current state only. Carry over tags, term, and isCore from the existing memory unless the new information warrants changing them.

**Create a new memory** when the new information:
- Covers a distinct fact that happens to be topically related (e.g. existing: "uses PostgreSQL for the database" vs new: "prefers Prisma as an ORM")
- Would violate the one-fact-per-memory principle if merged

**Both update and create** when part of the new information updates the existing fact and part introduces a genuinely separate fact.

**Leave unchanged** when the existing memory already fully captures the information. Return the existing memory exactly as-is and set newMemory to null.`,
        messages: [
            {
                role: userRole,
                content: `<existing_memory>
Summary: ${nearMemory.summary}${
    memoryConfig.includeQuote ? `\nQuote: ${nearMemory.quote}` : ''}${
    memoryConfig.includeSource ? `\nSource: ${nearMemory.source}` : ''}${
    memoryConfig.includeTags ? `\nTags: ${nearMemory.tags?.join(', ')}` : ''}${
    memoryConfig.includeCore ? `\nIsCore: ${nearMemory.isCore}` : ''}${
    memoryConfig.includeTerm ? `\nTerm: ${nearMemory.term}` : ''}
</existing_memory>

<candidate_memory>
Summary: ${newMemory.summary}${
    memoryConfig.includeQuote ? `\nQuote: ${newMemory.quote}` : ''}${
    memoryConfig.includeSource ? `\nSource: ${newMemory.source}` : ''}${
    memoryConfig.includeTags ? `\nTags: ${newMemory.tags?.join(', ')}` : ''}${
    memoryConfig.includeCore ? `\nIsCore: ${newMemory.isCore}` : ''}${
    memoryConfig.includeTerm ? `\nTerm: ${newMemory.term}` : ''}
</candidate_memory>

Compare these two memories and decide whether to update the existing memory, create a new separate memory, or both. Follow the decision criteria in your instructions.`,
            },
        ],
    }
}

export default {
    memoryExtraction,
    memoryMerge,
    relevantMemorySearch,
}
